apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gke
  template:
    metadata:
      labels:
        app: hello-gke
    spec:
      containers:
      - name: hello-gke-container
        image: gcr.io/mypoc-469116/hello-gke:v1
        ports:
        - containerPort: 8080
